pagopa/pagopa-checkout-auth-service

api-spec/v1/openapi.yaml
build.gradle.kts
src/main/kotlin/it/pagopa/checkout/authservice/telemetry/OpenTelemetryConfig.kt

- Added gradle tasks to generate classes from open api
- Added openapi definition for api as described here [doc](https://[pagopa.atlassian.net/wiki/spaces/I/pages/1443463171/DR+-+Autenticazione+in+Checkout+-+Fase+1](https://pagopa.atlassian.net/wiki/spaces/I/pages/1443463171/DR+-+Autenticazione+in+Checkout+-+Fase+1))
This is part of a bigger effort of implementing authenticated flow
Code gen, not requires testing

[CHK-3686] Openapi definition for new api

---

.github/actions/check-pr-semver-labels/action.yml
.github/workflows/check_pr.yml
.github/workflows/deploy.yml

- add github action for check PR after commit
- add github action for deploy after merge
The goal of this PR is to setup github actions

[CHK-3683] feat: add github actions

---

build.gradle.kts
helm/values-prod.yaml
helm/values-uat.yaml

fix: [CHK-3682] gradle fixes

---

helm/values-prod.yaml
helm/values-uat.yaml

fixing repository url for uat and prod environment

fix: [CHK-3682] fixing repository url for uat and prod environment

---

helm/values-uat.yaml

- fix ONEIDENTITY_BASE_URL config for uat

fix(oi-config): update ONEIDENTITY_BASE_URL for uat

---

api-spec/v1/openapi.yaml
src/main/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginController.kt
src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
src/test/kotlin/it/pagopa/checkout/authservice/controllers/AuthLoginControllerTest.kt
src/test/kotlin/it/pagopa/checkout/authservice/services/AuthenticationServiceTest.kt

Added implementation of POST /auth/logout API and related tests

[CHK-3762] feat(logout): logout session API implementation

---

.devops/azure-templates/helm-microservice-chart-deploy.yml
.devops/code-review-pipelines.yml
.devops/deploy-pipelines.yml

depends on https://github.com/pagopa/pagopa-checkout-tests/pull/109
- Added usage of newmann for deploy pipeline (dev)
This is part of a bigger effort aiming at introducing authenticated flow on checkout-fe
Manual, + newmann

[CHK-3811] Add usage of new Test collection in deploy pipeline - Dev Only

---

.devops/deploy-pipelines.yml

Add missing `endpoint` section in deploy pipeline
Add missing `endpoint` section in deploy pipeline
run deploy pipeline -> https://dev.azure.com/pagopaspa/pagoPA-projects/_build/results?buildId=203422&view=results

fix(deploy-pipeline): add missing endpoint

---

.devops/code-review-pipelines.yml
.devops/deploy-pipelines.yml

Depends on https://github.com/pagopa/pagopa-checkout-tests/pull/111
Added api test uat green

[CHK-3831] Add api test uat green

---

.devops/deploy-pipelines.yml

Explicit UAT condition to make api tests run even if release is skipped
Explicit UAT condition to make api tests run even if release is skipped

fix: uat tests condition

---

src/main/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/UserFiscalCode.kt
src/main/kotlin/it/pagopa/checkout/authservice/services/AuthenticationService.kt
src/test/kotlin/it/pagopa/checkout/authservice/repositories/redis/bean/auth/DomainObjectsTest.kt

Added factory method to create user fiscal code from EU format

[CHK-3845] fix(fiscalCode): handle EU fiscal code format

---

.devops/azure-templates/helm-microservice-chart-deploy.yml
.devops/deploy-pipelines.yml
helm/values-uat.yaml

Depends on 
https://github.com/pagopa/pagopa-checkout-tests/pull/113
Updated helm chart to support beta canary for tests
Updated deploy pipeline to include beta deploy

[CHK-3837] Added UAT tests blue instance

---

helm/values-prod.yaml

Configuration for PROD env with OneIdentity
Fix deployment replicas
Disable log exporter for PROD
Configuration for PROD env with OneIdentity
Fix deployment replicas
Disable log exporter for PROD

chore: OI configuration for PROD env

---

.github/workflows/semver_release.yaml
build.gradle.kts
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Chk 4016 trigger pipe

---

.github/workflows/semver_release.yaml

Skip semver step is skip release is set to true
Skip app version bump for ignore-for-release version bump
In case of skip release for a PR is true no bump should be made at all

fix: skip semver update if skip release is true

---

helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

This reverts commit 698d53b0e3642c8bfc36846bee23ffa38663a681.

Revert "Bump version [skip ci]"

---

.github/workflows/check_pr.yml

chore: trigger deploy pipeline

---

.github/workflows/semver_release.yaml
helm/Chart.yaml
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Fixed shell script to extract version in case of version bump
Fixed shell script to extract version in case of version bump

fix: version extraction shell script

---

.github/actions/check-pr-semver-labels/action.yml

chore: trigger pipeline

---

.devops/deploy-pipelines.yml

CHK-4226: remove uninstall uat blue

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml

Updated REDIS_HOST and REDIS_PASSWORD secrets
The goal is to migrate to redis standard to reduce costs. [Enable zone redundancy for Azure Cache for Redis](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-zone-redundancy)

[PIDM-914] feat(redis-standard): Migration to redis standard
